description = "Create a Conventional Commit message and execute the commit."

prompt = """
---
description: Create a Conventional Commit message and execute the commit.
---

Given the user's intent provided as an argument (which can be a short description of the changes), do this:

1.  Run `git add .` to stage all changes.
2.  Run `git status` to ensure there are changes staged for commit.
3.  If no files are staged, inform the user and stop.
4.  Run `git diff --staged` to analyze the exact changes.
5.  Based on the staged changes and the user's intent, formulate a high-quality commit message that strictly follows the Conventional Commits specification.
    - The format should be `type(scope): subject` followed by an optional body.
    - The `type` must be one of: feat, fix, build, chore, ci, docs, perf, refactor, revert, style, test.
    - The message should accurately summarize the changes.
6.  execute `git commit -m "<Generated-Message>"`.
7.  After the commit, run `git status` to confirm the working tree is clean.
"""
